name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: macos-latest
    steps:
      - name: Print string
        run: echo I have printed 1 string
      - name: Print 2 string
        run: |
          echo I have printed the first string
          echo I have printed the second string
